# Generated by Django 5.0 on 2025-01-04 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("still", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="email",
            old_name="subject",
            new_name="comments",
        ),
    ]
