# Generated by Django 5.0 on 2025-01-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("still", "0002_rename_subject_email_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="comments",
            field=models.TextField(max_length=500),
        ),
    ]
