# Generated by Django 5.0 on 2025-01-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("still", "0005_remove_email_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="comments",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
