# Generated by Django 5.0 on 2025-01-09 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("still", "0006_alter_email_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Email",
            new_name="Message",
        ),
    ]
