# Generated by Django 5.0 on 2025-04-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('still', '0008_message_id_alter_message_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=100)),
                ('company', models.TextField()),
                ('education', models.BooleanField(default=False)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('skills', models.JSONField()),
            ],
        ),
    ]
