# Generated by Django 5.0 on 2025-04-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('still', '0009_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['created_at']},
        ),
    ]
